#!/bin/bash

=(){
    echo $@
}

# parse json
jsonval(){
    temp=`echo $json | sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g' | grep -w $1|head -1`;
    = ${temp}|awk -F '|' '{print $2}';
}

# LOG PRINT: To check network healthy.
netCheck(){
    URL_TMP=`echo $1 | sed s'/https:\/\///'`
    = "-----------------CHECK THE NETWORK CONNECTIONS-----------------"
    = ">>>>   `printNow` environment=$URL_TMP"
    if [ "$(timeout --signal=9 5 telnet $URL_TMP 443 | grep Connect)" == "" ]
    then
      = ">>>>   `printNow` connect $URL_TMP 443 failed"
    else
      = ">>>>   `printNow` connect $URL_TMP 443 successful"
    fi
    = "---------------------------------------------------------------"
}

# LOG PRINT : print current time
printNow(){
    = `date +[%Y-%m-%d\ %H:%M:%S]`
}

# Check file if exists.
checkFile(){
    if [[ -s $1 ]];
    then
        = ">>>>   `printNow` $1 has been generated."
        = ">>>>   `printNow` Take a look: `ls -al $1`"
        temp_01=`head -1 $1`
        = ">>>>   `printNow` First line : ${temp_01:0:100}"
    else
        = "[WARNNING]   `printNow` $1 not generated, please check the status!"
        = "[WARNNING]   `printNow` Take a look: `ls -al $1`"
    fi;
}

